### ISSUE TITLE
Game stops when our nexus is eliminated

### ISSUE THREAD

**Issue by sws503** [Archiatrus/commandcenter#6]
![nexus bomb](https://user-images.githubusercontent.com/33389150/37017009-376b5456-2152-11e8-994c-a8b14e8ace70.png)

**Comment by Archiatrus** [comment]
Thanks for letting me know. I will look into it.

**Comment by Archiatrus** [comment]
First of all, sorry that it took me so long to find time to look into this.

The problem was a cyclic build order lock. It wanted to build a probe, which needs a nexus, which needs a probe etc. I fixed this with 3afb3c8c25097ffdfd1a2096f093eafd9dfc5121. Thanks again for reporting this.
